language: node_js

node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "11"

dist: xenial
cache: yarn

script: yarn test:ci

jobs:
  include:
    - stage: doctoc-check
      install: npm install -g doctoc
      if: type = pull_request OR branch = master
      script:
        - cp README.md README.md.orig
        - npm run doctoc
        - diff -q README.md README.md.orig
