language: node_js
dist: trusty
cache: yarn
env:
  global:
    - CXX=g++-4.8

jobs:
  include:
    - env: task=npm-test
      node_js:
        - 6
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
        - export PATH="$HOME/.yarn/bin:$PATH"
    - env: task=npm-test
      node_js:
        - 7
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
        - export PATH="$HOME/.yarn/bin:$PATH"
